[project]
name = "mrm-chat-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "djangorestframework>=3.16.1",
    "channels>=4.3.1",
    "daphne>=4.2.1",
]
