# Generated by Django 5.2.7 on 2025-10-15 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_alter_chat_name_alter_chat_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the AI conversation', max_length=255)),
                ('system_prompt', models.TextField(default='You are a helpful assistant.', help_text='System prompt for ChatGPT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_chat', models.ForeignKey(blank=True, help_text='Optional: Related user-to-user chat for context', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chats', to='chat.chat')),
                ('user', models.ForeignKey(help_text='User participating in this AI chat', on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Role of the message sender', max_length=10)),
                ('content', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('ai_chat', models.ForeignKey(help_text='The AI chat this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_chat.aichat')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
